name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    env:
      IMAGE: ${{ secrets.DOCKER_USERNAME }}/podinfo
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup git config
      uses: fregante/setup-git-user@v1

    - name: Restore Go cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Run unit tests
      run: make test

    - name: Bump version
      id: version
      uses: phish108/autotag-action@1.1.51
      with:
        github-token: ${{ secrets.GH_TOKEN}}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ steps.version.outputs.new-tag }}
          ${{ env.IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Checkout configuration
      uses: actions/checkout@v3
      with:
        repository: JRuedas/tfm-argocd-apps
        path: ./tfm-argocd-apps
        submodules: recursive

    - name: Update Helm chart version
      run: |
          version=$(cat ./tfm-argocd-apps/charts/jruedas-podinfo/Chart.yaml | grep -m 1 appVersion: | awk '{print $2}')
          sed -i "0,/tag: $version/{s/tag: $version/tag: ${{ steps.version.outputs.new-tag }}/}" ./tfm-argocd-apps/charts/jruedas-podinfo/values.yaml
          sed -i "s/appVersion: $version/appVersion: ${{ steps.version.outputs.new-tag }}/" ./tfm-argocd-apps/charts/jruedas-podinfo/Chart.yaml

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Version updated
        file_pattern: ./charts/podinfo/values*.yaml ./charts/podinfo/Chart.yaml