name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    env:
      IMAGE: jruedas92/podinfo
    runs-on: ubuntu-latest
    - name: Prepare
      id: prep
      run: |
        VERSION=sha-${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi
        echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo ::set-output name=VERSION::${VERSION}
    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v3

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          ${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_ID }}      
        labels: ${{ steps.meta.outputs.labels }}