name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    env:
      IMAGE: ${{ secrets.DOCKER_USERNAME }}/podinfo
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Restore Go cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Run unit tests
      run: make test
    - uses: phish108/autotag-action@1.1.51
      id: version
      with:
        github-token: ${{ secrets.GH_TOKEN}}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ steps.version.outputs.new-tag }}
          ${{ env.IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}