name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'pkg/version/version.go'

jobs:
  docker:
    env:
      IMAGE: ${{ secrets.DOCKER_USERNAME }}/podinfo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup git config
      uses: fregante/setup-git-user@v1

    - name: Restore Go cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Run unit tests
      run: make test

    - name: Bump version
      id: version
      uses: phish108/autotag-action@1.1.51
      with:
        github-token: ${{ secrets.GH_TOKEN}}

    - name: Update source code version
      run: |
          version=$(cat ./pkg/version/version.go | grep 'VERSION' pkg/version/version.go | awk '{ print $$4 }' | tr -d '"' | awk '{print $4}')
          sed -i "s/$version/${{ steps.version.outputs.new-tag }}/" ./pkg/version/version.go

   - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ steps.version.outputs.new-tag }}
          ${{ env.IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Commit new version and push changes to source code repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Version updated ${{ steps.version.outputs.new-tag }}
        file_pattern: ./pkg/version/version.go

    - name: Checkout configuration repository
      uses: actions/checkout@v3
      with:
        repository: JRuedas/tfm-argocd-apps
        path: ./tfm-argocd-apps
        submodules: recursive
        token: ${{ secrets.GH_TOKEN}}

    - name: Update configuration repository version
      run: |
          version=$(cat ./tfm-argocd-apps/charts/jruedas-podinfo/Chart.yaml | grep -m 1 appVersion: | awk '{print $2}')
          sed -i "0,/tag: $version/{s/tag: $version/tag: ${{ steps.version.outputs.new-tag }}/}" ./tfm-argocd-apps/charts/jruedas-podinfo/values.yaml
          sed -i "s/appVersion: $version/appVersion: ${{ steps.version.outputs.new-tag }}/" ./tfm-argocd-apps/charts/jruedas-podinfo/Chart.yaml

    - name: Commit new version and push changes to configuration repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: ./tfm-argocd-apps
        commit_message: Version updated ${{ steps.version.outputs.new-tag }}
        file_pattern: ./charts/jruedas-podinfo/values.yaml ./charts/jruedas-podinfo/Chart.yaml